### PR TITLE
fix not escaped dollar signs in regex snippet

### LINKED ISSUE #62: Dollar sign bug
When the dollar sign is matched by the trigger, it drops the surrounding section: https://gist.github.com/eytienne/ab025fb1287b73a0c79e1de885835759

### PR DESCRIPTION
**Pull request by eytienne**
It fixes #62

### CODE REVIEW

**Comment by draivin** [comment]
Hello @eytienne, the escaping should be done at parsing time, we even have a function defined for that purpose over here: https://github.com/draivin/hsnips/blob/ade14c5426c0b5c17b115d3d8ef1b3f200a74130/src/parser.ts#L38

**Comment by draivin** [comment]
I misunderstood the escaping you intended to fix, the problem here is happening the first time a dynamic snippet is being inserted.

This can be fixed by escaping when the snippet string is first generated, that is, escaping all the strings in the `blocks` array located over here:
https://github.com/draivin/hsnips/blob/ade14c5426c0b5c17b115d3d8ef1b3f200a74130/src/hsnippetInstance.ts#L78

**Comment by draivin** [comment]
Even so, I'm not entirely sure that is undesirable behavior, as it allows javascript code to dynamically insert tab stops to the snippet expansion. I'll think about this a little more and get back to you.

**Comment by 1024th** [comment]
I think this is not a bug and should not be "fixed". It's better to let the JavaScript code inside snippet body to determine whether to escape the dollar sign in original string. Maybe we need to add a note to README to remind people to escape the dollar sign if they need, but we shouldn't escape the return value of the JavaScript code. That ruins JavaScript interpolation's power to dynamically insert tab stops. (Also ruins my snippets.)

**Comment by draivin** [comment]
Hey @1024th, sorry for getting back so late, but there is an alternative way to introduce interpolation inside javascript blocks, as can be seen [here](https://github.com/draivin/hsnips/issues/97#issuecomment-997126076), it is just not in the readme yet!

**Comment by 1024th** [comment]
Thanks a lot! That's exactly what I need :)

**Pull request merged**
